# Generated by Django 5.2.15 on 2026-06-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='USDT Wallet', max_length=100)),
                ('trc20_wallet', models.CharField(max_length=255)),
                ('usd_rwf_rate', models.DecimalField(decimal_places=2, default=1500, max_digits=10)),
                ('mtn_code', models.CharField(default='1861343', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
