# Generated by Django 5.2.15 on 2026-06-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletuser',
            name='locked_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
