# Generated by Django 5.2.15 on 2026-06-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'DEPOSIT'), ('BUY', 'BUY'), ('SELL', 'SELL'), ('INTERNAL', 'INTERNAL'), ('EXTERNAL', 'EXTERNAL'), ('INTERNSHIP', 'INTERNSHIP')], max_length=20),
        ),
    ]
