# Generated by Django 5.2.15 on 2026-06-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rwf_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
