# Generated by Django 5.2.15 on 2026-06-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_rwf_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver_wallet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
