# Generated by Django 5.2.15 on 2026-06-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver_wallet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
