# Generated by Django 5.2.15 on 2026-06-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_buyorder_deposit_sellorder_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deposit',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellorder',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
