# Generated by Django 5.2.15 on 2026-06-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_buyorder_transaction_deposit_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='visible_to_admin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
