# Generated by Django 5.2.15 on 2026-06-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_transaction_visible_to_admin_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='visible_to_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deposit',
            name='visible_to_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellorder',
            name='visible_to_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='visible_to_admin',
            field=models.BooleanField(default=False),
        ),
    ]
