# Generated by Django 5.2.15 on 2026-06-23 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_walletuser_locked_balance'),
        ('transactions', '0011_buyorder_visible_to_admin_deposit_visible_to_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_username', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.walletuser')),
            ],
        ),
    ]
